participant_tsv: participant_id.tsv
input_dir: /home/myousif9/scratch/hcp_unfolding3_jdkrek
boundary: /scripts/BigBrain_ManualSubfieldsUnfolded.mat
singularity: /scratch/myousif9/singularity/gif_your_nifit_miykael.sif

coords:
  - AP
  - IO
  - PD

features:
  - GI
  - streamlengths
  - qMap
  
unfold_mat:
  - surf

hemi:
  - L

cmap: plasma